[workspace]
resolver = "3"
members = ["crates/firmware", "crates/proto"]
default-members = ["crates/proto"]

[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"

[profile.dev.package.esp-radio]
opt-level = 3

[profile.dev.package.esp-storage]
opt-level = 3
